---
title: "Emissions Over Time"
author: "Zhang Zhenglin"
output:
  pdf_document:
    toc: yes
editor_options:
  markdown:
    wrap: sentence
---

# Necessary libraries

```{r message=FALSE,warning=FALSE}
library(knitr)
library(ggplot2)
theme_set(theme_bw())
library(emmeans)
library(multcomp)
library(PLS205)
library(lme4)
library(lmerTest)
library(multcompView)
library(car)
library(Rmisc) 
library(dplyr) #https://r4ds.had.co.nz/ (Chapter 3, Chapter 5, look at filter and select)
# https://bookdown.org/ansellbr/WEHI_tidyR_course_book/
library(stringr) 
library(data.table)
library(GGally)
library(formatR)
library(readxl)
library(ggpubr)
library(lubridate)
```

# Data Organisation

## Read from excel

```{r}
#read directly from the directory where I generated the files from
master <- read_excel("D:/Academics/UC Davis/School Work/Linquist Lab/Data/R stats/GHG and MAOM POM/Seasonal cumulative calculations (16 Jul 2024)/Daily_Flux_Mastersheet_Final_DoNotEdit.xlsx", sheet = 1)
str(master)
```

# 2021/22 Fsummer/winter

```{r}

F_2021_22 <- master %>%
  filter(Date >= as.POSIXct("2021-07-10") & Date <= as.POSIXct("2022-05-12"))%>% 
  filter (Plot == c(402, 505, 601))

CH4_g_ha_day_2021_graphing <- F_2021_22 %>% group_by(Date) %>% 
mutate(CH4_g_ha_day_sd = sd(CH4_g_ha_day)) %>% 
  summarise(CH4_g_ha_day = mean(CH4_g_ha_day),
            CH4_g_ha_day_sd = mean(CH4_g_ha_day_sd))

gas_time_2021_graph <- ggplot(CH4_g_ha_day_2021_graphing, aes(x= Date, y = CH4_g_ha_day))+
  geom_point()+
  geom_line()+
  geom_errorbar(aes(ymin=CH4_g_ha_day-CH4_g_ha_day_sd, ymax=CH4_g_ha_day+CH4_g_ha_day_sd))+
  #scale_color_manual(values = c("#FFCC66"))+
  labs(y = expression("Daily CH"[4]~"Flux (g ha"^-1~" day"^-1~")")) +
  scale_y_continuous(limits = c(-200, 200), 
                     expand = c(0, 0),
                     )+
  ggtitle("2021/22") +
  scale_x_datetime(name = "", date_breaks = "1 month", date_labels = "%b %Y")+
  theme_classic()+
  theme(legend.title = element_blank(),
        axis.text.x = element_text(size=10,angle=50, hjust=1.2, vjust=1.2))+
  geom_vline(xintercept = as.POSIXct(c("2021-10-12")), linetype = "dashed", color = "black", size =0.4)+
  annotate(
  "text",
  x = as.POSIXct(c("2021-09-15")),  # X-axis positions for annotations
  y = c(100),  # Y-axis positions for annotations
  label = expression("F"[summer]),
  size = 4,
  vjust = 0  # Adjust vertical position of asterisks
)+
  annotate(
  "text",
  x = as.POSIXct(c("2022-02-10")),  # X-axis positions for annotations
  y = c(100),  # Y-axis positions for annotations
  label = expression("F"[winter]),
  size = 4,
  vjust = 0  # Adjust vertical position of asterisks
)

gas_time_2021_graph

ggsave(gas_time_2021_graph, filename = "gas_time_2021_graph.png", height = 15, width = 60, units = "cm", dpi=1000)

```

# 2022/23 F_summer_winter 

```{r}
F_2022_23 <- master %>%
  filter(Date >= as.POSIXct("2022-05-30") & Date <= as.POSIXct("2023-04-19"))%>% 
  filter (Plot %in% c(209, 307, "K1"))

CH4_g_ha_day_2022_graphing <- F_2022_23 %>% group_by(Date) %>% 
mutate(CH4_g_ha_day_sd = sd(CH4_g_ha_day)) %>% 
  summarise(CH4_g_ha_day = mean(CH4_g_ha_day),
            CH4_g_ha_day_sd = mean(CH4_g_ha_day_sd))

gas_time_2022_graph <- ggplot(CH4_g_ha_day_2022_graphing, aes(x= Date, y = CH4_g_ha_day))+
  geom_point()+
  geom_line()+
  geom_errorbar(aes(ymin=CH4_g_ha_day-CH4_g_ha_day_sd, ymax=CH4_g_ha_day+CH4_g_ha_day_sd))+
  #scale_color_manual(values = c("#FFCC66"))+
  labs(y = expression("Daily CH"[4]~"Flux (g ha"^-1~" day"^-1~")")) +
  scale_y_continuous(limits = c(-200, 200), 
                     expand = c(0, 0),
                     )+
  ggtitle("2022/23") +
  scale_x_datetime(name = "", date_breaks = "1 month", date_labels = "%b %Y")+
  theme_classic()+
  theme(legend.title = element_blank(),
        axis.text.x = element_text(size=10,angle=50, hjust=1.2, vjust=1.2))+
  geom_vline(xintercept = as.POSIXct(c("2022-10-20")), linetype = "dashed", color = "black", size =0.4)+
  annotate(
  "text",
  x = as.POSIXct(c("2022-08-15")),  # X-axis positions for annotations
  y = c(100),  # Y-axis positions for annotations
  label = expression("F"[summer]),
  size = 4,
  vjust = 0  # Adjust vertical position of asterisks
)+
  annotate(
  "text",
  x = as.POSIXct(c("2023-02-10")),  # X-axis positions for annotations
  y = c(100),  # Y-axis positions for annotations
  label = expression("F"[winter]),
  size = 4,
  vjust = 0  # Adjust vertical position of asterisks
)

gas_time_2022_graph

ggsave(gas_time_2022_graph, filename = "gas_time_2022_graph.png", height = 15, width = 60, units = "cm", dpi=1000)

```


# Combine Fsummer_winter into one figure


```{r}
all_years_vertical <- ggarrange(gas_time_2021_graph, gas_time_2022_graph,
                    #labels = c("2021", "2022", "2023"),
                    nrow = 2,
                    common.legend = TRUE,
                    legend= "bottom")

ggsave(all_years_vertical, filename = "all_years_vertical.jpg", height = 30, width = 30, units = "cm", dpi=300)

all_years_horizontal <- ggarrange(gas_time_2021_graph, gas_time_2022_graph,
                    #labels = c("2021", "2022", "2023"),
                    ncol = 2,
                    common.legend = TRUE,
                    legend= "bottom")

ggsave(all_years_horizontal, filename = "all_years_horizontal.jpg", height = 15, width = 70, units = "cm", dpi=1000)
```
