---
title: "Climate"
author: "Zhang Zhenglin"
output:
  pdf_document:
    toc: yes
editor_options:
  markdown:
    wrap: sentence
---

# Necessary libraries

```{r message=FALSE,warning=FALSE}
library(knitr)
library(ggplot2)
theme_set(theme_bw())
library(emmeans)
library(multcomp)
library(PLS205)
library(lme4)
library(lmerTest)
library(multcompView)
library(car)
library(Rmisc) 
library(dplyr) #https://r4ds.had.co.nz/ (Chapter 3, Chapter 5, look at filter and select)
# https://bookdown.org/ansellbr/WEHI_tidyR_course_book/
library(stringr) 
library(data.table)
library(GGally)
library(formatR)
library(readxl)
library(paletteer )

```

# Monthly

## Read from excel

```{r}
#read directly from the directory where I generated the files from
monthly <- read_excel("D:/Academics/UC Davis/School Work/Linquist Lab/Data/R stats/GHG and MAOM POM/Climate_graph/monthly.xlsx", sheet = 1)
monthly <- monthly %>%
  select(where(~ all(complete.cases(.))))

monthly$Precipitation_mm <- monthly$"Total Precip (mm)"
monthly$Temperature_C <- monthly$"Avg Air Temp (C)"

monthly$Month_Year <- monthly$"Month Year"

monthly <- monthly %>%
  mutate(Year = format(Month_Year, "%Y"))

head(monthly)

str(monthly)
```

```{r}
climate_graph <-
ggplot(monthly, aes(x=Month_Year))+
  #geom_point()+
  geom_bar(stat = "identity", aes(y = Precipitation_mm, fill="Precipitation_mm"), fill="#808080FF")+
  geom_line(aes(y = Temperature_C*3.5, color = "Temperature_C"), color="Black", size=0.7)+
  geom_point(aes(y = Temperature_C*3.5), color="Black", size=2)+
  scale_x_datetime(
    name = "",
    date_breaks = "1 month",  # Breaks at every month
    date_labels = "%b",  # Format as abbreviated month names
    #limits = as.POSIXct(c("2020-09-30", "2023-11-5")),
    expand = c(0.01, 0)
  ) +
  scale_y_continuous(
    expression("Monthly Precipitation (mm)"),
    sec.axis = sec_axis(~ ./3.5 , name = expression("Average Monthly Temperature   " (degree*C))),
    expand = c(0, 0),
    breaks = seq(0, 160, by = 20),
    limits = c(0, 160)
  )+
  theme_classic()+
  theme(text = element_text(size=10),
        axis.text.x = element_text(size=12,angle=50, hjust=1.5, vjust=1.4),
        axis.text.y = element_text(size=13))+
  geom_vline(xintercept = as.POSIXct(c("2020-12-16","2021-12-16","2022-12-16")), linetype = "dashed", color = "black", size =0.6)+
  annotate(
  "text",
  x = as.POSIXct(c("2021-06-20")),  # X-axis positions for annotations
  y = c(150),  # Y-axis positions for annotations
  label = "2021",
  size = 4,
  vjust = 0  # Adjust vertical position of asterisks
)+
  annotate(
  "text",
  x = as.POSIXct(c("2020-10-28")),  # X-axis positions for annotations
  y = c(150),  # Y-axis positions for annotations
  label = "2020",
  size = 4,
  vjust = 0  # Adjust vertical position of asterisks
)+
  annotate(
  "text",
  x = as.POSIXct(c("2022-06-20")),  # X-axis positions for annotations
  y = c(150),  # Y-axis positions for annotations
  label = "2022",
  size = 4,
  vjust = 0  # Adjust vertical position of asterisks
)+
  annotate(
  "text",
  x = as.POSIXct(c("2023-06-20")),  # X-axis positions for annotations
  y = c(150),  # Y-axis positions for annotations
  label = "2023",
  size = 4,
  vjust = 0  # Adjust vertical position of asterisks
)+
   theme(axis.text = element_text(size = 16), axis.title = element_text(size=16))

ggsave(climate_graph, filename = "climate_graph.png", height = 15, width = 30, units = "cm", dpi = 1000)

ggsave(climate_graph, filename = "climate_graph_LowRes.png", height = 15, width = 30, units = "cm", dpi = 400)

```

```{r}
paletteer_d("MoMAColors::Abbott")
```


```{r}
ggplot(monthly, aes(x=Month_Year,Precipitation_mm, fill = "Precipitation_mm"))+
  #geom_point()+
  geom_bar(stat = "identity", fill="#808080FF")
```

